export const FATCH_BLOG_POSTS_REQUEST = 'FATCH_BLOG_POSTS_REQUEST';
export const FATCH_BLOG_POSTS_SUCCESS = 'FATCH_BLOG_POSTS_SUCCESS';
export const FATCH_BLOG_POSTS_FAILURE = 'FATCH_BLOG_POSTS_FAILURE';